import { ROLES, type NombreRol } from "@/lib/constants/roles";
import { PERMISOS, type Permiso } from "@/lib/permissions/permissions";

export const PERMISOS_POR_ROL: Record<NombreRol, Permiso[]> = {
  [ROLES.ADMINISTRADOR]: Object.values(PERMISOS),

  [ROLES.COORDINADOR]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_INVENTARIO,
    PERMISOS.VER_PRESTAMOS,
    PERMISOS.CREAR_PRESTAMO,
    PERMISOS.EDITAR_PRESTAMO,
    PERMISOS.REGISTRAR_DEVOLUCION,
    PERMISOS.VER_MATRIMONIOS,
    PERMISOS.CREAR_MATRIMONIO,
    PERMISOS.EDITAR_MATRIMONIO,
    PERMISOS.VER_REPORTES,
  ],

  [ROLES.INVENTARIO]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_INVENTARIO,
    PERMISOS.CREAR_ARTICULO,
    PERMISOS.EDITAR_ARTICULO,
    PERMISOS.DESACTIVAR_ARTICULO,
    PERMISOS.VER_PRESTAMOS,
    PERMISOS.CREAR_PRESTAMO,
    PERMISOS.EDITAR_PRESTAMO,
    PERMISOS.REGISTRAR_DEVOLUCION,
    PERMISOS.VER_REPORTES,
  ],

  [ROLES.SECRETARIA]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_MATRIMONIOS,
    PERMISOS.CREAR_MATRIMONIO,
    PERMISOS.EDITAR_MATRIMONIO,
    PERMISOS.VER_PRESTAMOS,
  ],

  [ROLES.TESORERIA]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_REPORTES,
  ],
};

export function tienePermiso(
  rol: NombreRol | null | undefined,
  permiso: Permiso,
): boolean {
  if (!rol) return false;

  return PERMISOS_POR_ROL[rol]?.includes(permiso) ?? false;
}